config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'gadgets#index'
  resources :gadgets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gadget.rb
class Gadget < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gadgets_controller.rb
class GadgetsController < ApplicationController

  def index
    @gadgets = Gadget.all
  end

  def create
    Gadget.create(gadget_params) # Sends gadget_name & description to be saved in the DB
    redirect_to root_path # Once info is submitted, take user back to index page
  end

  private

  def gadget_params # Pulls the values of gadget_name & description from the form
    params.require(:gadget).permit(:gadget_name, :description, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gadgets_helper.rb
module GadgetsHelper
end

app/views/gadgets/index.html.erb
<h1>Essential &rsquo;80s Gadgets</h1>

<div class="container"> <!-- Compulsory Bootstrap container, but no rows as only 1 column -->
    
  <div class="links text-right">
    <%= link_to 'Add A Gadget', new_gadget_path, data: {toggle: 'modal', target: '#myModal'} %>
  </div> <!-- class="links" -->

  <br class="clear" />

  <% @gadgets.each do |gadget| %> <!-- Rails stepping through each gadget in the db table -->
    <div class="photo"> <!-- Container for image -->
      <%= image_tag gadget.image.url, class: 'img-fluid' %> <!-- Render image -->
      <!-- Was gadget.image_filename, but no longer storing images in app/assets/images -->
    </div> <!-- class="photo" -->
    
    <div class="text-container"> <!-- Container for text -->
      <h2><%= gadget.gadget_name %></h2> <!-- Render name field -->
      <p><%= gadget.description %></p> <!-- Render description field -->
    </div> <!-- class="text-container" -->

    <br class="clear" />
    <br />
  <% end %> <!-- End of Rails code -->
</div> <!-- class="container" -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EightiesGadgets</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      @import url('https://fonts.googleapis.com/css?family=Press+Start+2P');
      @import url('https://fonts.googleapis.com/css?family=Quantico');
    </style> 
  </head>

  <body>
    <!-- Modal: "Add An '80s Gadget" -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"> <!-- Bootstrap modal, which fades in and out -->
      <div class="modal-dialog" role="document"> <!-- Inner container -->
        <div class="modal-content"> <!-- Another container, actual repository for modal content -->
          <div class="modal-header"> <!-- First of three sections -->
            <h4 class="modal-title" id="myModalLabel">Add An &rsquo;80s Gadget</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button> <!-- "x" button to close window -->
          </div> <!-- class="modal-header" -->
          <%= simple_form_for Gadget.new do |f| %> <!-- Rails code steps in here... -->
            <div class="modal-body"> <!-- Second of three sections -->
              <%= f.input :gadget_name, label: "What is the name of the gadget?" %>
              <%= f.input :description %>
              <%= f.input :image, label: "Image (Preferably about 240px high)..." %>
            </div> <!-- class="modal-body" -->
            <div class="modal-footer"> <!-- Third of three sections, contains 2 buttons -->
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit 'Create', class: 'btn btn-info' %>
            </div> <!-- class="modal-footer" -->
          <% end %> <!-- End of Rails code -->
        </div> <!-- class="modal-content" -->
      </div> <!-- class="modal-dialog" -->
    </div> <!-- class="modal fade" -->

    <%= yield %> <!-- Insert point for page text -->
  </body>
</html>